### ISSUE TITLE
Teach twet file:// urls

### ISSUE THREAD

**Issue by quite** [quite/twet#2]
I was thinking of using #twet for taking shortish one-line notes. I added tag completion to that end. Now I realized that to make use of that locally as I want, I would have to teach it file:// urls.

**Comment by gbmor** [comment]
Sounds like a nifty potential use for `twet`. Are you trying to allow it to 'follow' local files and have them show up in your timeline?

**Comment by quite** [comment]
Precisely. And, following feed(s) would also be necessary for giving the tag
completion something to complete on.
